name: Node.js Package

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build pkg
        run: |
          cargo install wasm-pack
          wasm-pack build --target web
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Publish pkg 
        run: |
          cd pkg
          rm package.json
          cp ../package.json.publish package.json
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
