name: cargo test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "releases/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --release --no-default-features --features "console_error_panic_hook"
